default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: 5

development:
  <<: *default
  database: ticket_desk
  username: your_pg_username
  password: your_pg_password

test:
  <<: *default
  database: ticket_desk_test
  username: your_pg_username
  password: your_pg_password

production:
  <<: *default
  database: ticket_desk
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
